# From https://github.com/thedodd/trunk/blob/master/Trunk.toml

[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = true
# The output dir for all final assets.
dist = "docs"
# The public URL from which assets are to be served.
public_url = "/"
# Whether to include hash values in the output file names.
filehash = true
# Whether to inject scripts (and module preloads) into the finalized output.
inject_scripts = true

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = []
# Paths to ignore.
ignore = ["src/plots/cli/facebook.rs"]

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8081
# Open a browser tab once the initial build is complete.
open = true
# Disable auto-reload of the web app.
no_autoreload = false

# [tools]
# # Default dart-sass version to download.
# sass = "1.54.9"
# # Default wasm-bindgen version to download.
# wasm_bindgen = "0.2.83"
# # Default wasm-opt version to download.
# wasm_opt = "version_110"
# # Default tailwindcss-cli version to download.
# tailwindcss = "3.3.2"

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp ./target/main.css $TRUNK_STAGING_DIR/"]
