name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build wasm
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'       
          run: trunk build --release --dist docs

      - name: Add and commit build 
        uses: EndBug/add-and-commit@v9 
        with:
          add: 'docs'
